ETrade.UI/Controllers/AuthController.cs
using ETrade.Ent;
using ETrade.UI.Session;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ETrade.UI.Controllers
{
    public class AuthController : BaseController
    {
        private readonly Users user;

        public AuthController(IUow uow, Users user) : base(uow)
        {
            this.user = user;
        }

        public IActionResult Register()
        {
            return View(user);
        }
        [HttpPost]
        public IActionResult Register(Users u)
        {
            Uow.userRepos.Register(u);
            //SessionHelper.SetObjectAsJson(HttpContext.Session, "user", u);
            //Data.LoginUser = SessionHelper.GetObjectFromJson<Users>(HttpContext.Session, "user");

            Uow.Commit();
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            return View(user);
        }
        [HttpPost]
        public IActionResult Login(Users u)
        {
            var loginUser = Uow.userRepos.Login(u);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "user", loginUser);
            SessionData.LoginUser = loginUser;
            if (SessionData.LoginUser.isAdmin == true)
            {
                return RedirectToAction("Admin", "Admin");

            }
            else
            {
                return RedirectToAction("Index", "Home");

            }

        }
        public IActionResult Logout()
        {
			Users users = null;
			SessionHelper.SetObjectAsJson(HttpContext.Session, "user", user);
			SessionData.LoginUser = SessionHelper.GetObjectFromJson<Users>(HttpContext.Session, "user");
			return RedirectToAction("Index", "Home");
			
        }
    }
}

ETrade.UI/Controllers/CategoriesController.cs
using ETrade.UI.Models.ViewModel;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class CategoriesController : BaseController
    {

        private readonly CategoriesModel model;

        public CategoriesController(IUow uow, CategoriesModel model) : base(uow)
        {

            this.model = model;
        }

        public IActionResult List()
        {
            return View(Uow.catRepos.GetCategories());
        }
        public IActionResult Create()
        {
            model.Text = "Save";
            model.Head = "New Categories";
            model.Class = "btn btn-outline-success my-2";

            return View("Crud", model);
        }
        [HttpPost]
        public IActionResult Create(CategoriesModel model)
        {
            
            Uow.catRepos.Add(model.Categories);
            Uow.Commit();
            return RedirectToAction("List");
        }
        public IActionResult Update(Guid Id)
        {
            model.Text = "Save";
            model.Head = "Update Categories";
            model.Class = "btn btn-outline-success my-2";
            model.Categories = Uow.catRepos.Find(Id);

            return View("Crud", model);
        }
        [HttpPost]
        public IActionResult Update(CategoriesModel model)
        {

            Uow.catRepos.Update(model.Categories);
            Uow.Commit();
            return RedirectToAction("List");
        }
        public IActionResult Delete(Guid Id)
        {

            Uow.catRepos.Delete(Uow.catRepos.Find(Id));
            Uow.Commit();
            return RedirectToAction("List");
        }
        
    }
}

ETrade.UI/Controllers/FoodController.cs
using ETrade.DTO;
using ETrade.UI.Models.ViewModel;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
	public class FoodController : BaseController
	{
		private readonly FoodsModel model; 
		

		public FoodController(IUow uow, FoodsModel model) : base(uow)
		{
			this.model = model;
		}

		
		public IActionResult List()
		{
			return View(Uow.foodRepos.GetFoods());
		}
		public IActionResult Create()
		{
			model.Text = "Save";
			model.Head = "New Foods";
			model.Class = "btn btn-outline-success my-2";
			model.Cats = Uow.catRepos.GetCategories();
			return View("Crud", model);
		}
		[HttpPost]
		public IActionResult Create(FoodsModel model)
		{

			Uow.foodRepos.Add(model.Foods);
			Uow.Commit();
			return RedirectToAction("List");
		}
		public IActionResult Update(Guid Id)
		{
			model.Text = "Save";
			model.Head = "Update Properties";
			model.Class = "btn btn-outline-success my-2";
			model.Foods = Uow.foodRepos.Find(Id);
			model.Cats = Uow.catRepos.GetCategories();

			return View("Crud", model);
		}
		[HttpPost]
		public IActionResult Update(FoodsModel model)
		{

			Uow.foodRepos.Update(model.Foods);
			Uow.Commit();
			return RedirectToAction("List");
		}
		public IActionResult Delete(Guid Id)
		{
			Uow.foodRepos.Delete(Uow.foodRepos.Find(Id));
			Uow.Commit();
			return RedirectToAction("List");
		}
	}
}

ETrade.UI/Controllers/OrdersController.cs
using ETrade.Ent;
using ETrade.UI.Session;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class OrdersController : BaseController
    {
		private readonly Orders orders;

		public OrdersController(IUow uow, Orders orders) : base(uow)
        {
			this.orders = orders;
		}
        public IActionResult List()
        {
			SessionData.LoginUser = SessionHelper.GetObjectFromJson<Users>(HttpContext.Session, "user");
			return View(Uow.orderRepos.GetOrders(SessionData.LoginUser.UserId));
        }
		public IActionResult Create()
		{
			orders.isDelivered = false;
			orders.CreatedDate = DateTime.Now;
			orders.TotalPrice = 0;
			orders.LastUpdated = DateTime.Now;
			SessionData.LoginUser = SessionHelper.GetObjectFromJson<Users>(HttpContext.Session, "user");
			orders.UserId = SessionData.LoginUser.UserId;
			orders.ShippingAddress = SessionData.LoginUser.ShipAddress;
			Uow.orderRepos.Add(orders);
			Uow.Commit();
			return RedirectToAction("List", "OrderDetails", new {Id = orders.OrderId});
		}
	}
}

ETrade.UI/Views/Shared/_Layout.cshtml
@using ETrade.UI.Session;
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ETrade.UI</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ETrade.UI</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="List">Orders</a>
						</li>
						
						@if(SessionData.LoginUser.isAdmin == true)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admin">Admin</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="List">Foods</a>
							</li>
						}

				
					</ul>
					@if (!string.IsNullOrEmpty(SessionData.LoginUser.UserName))
					{
						<ul class="nav pull-right">
							<li class="divider-vertical"></li>
							<div class="dropdown">
								<button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								 Welcome @SessionData.LoginUser.UserName
								</button>
								<ul class="dropdown-menu">
									<li><a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a></li>
									<li><a class="dropdown-item" href="#">Help</a></li>
									
								</ul>
							</div>
						</ul>
					}
					else
					{
						<ul class="nav pull-right">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
							</li>
						</ul>

					}
				</div>

			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ETrade.UI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ETrade.UI</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ETrade.UI</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="List">Foods</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="List">Properties</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="List">Categories</a>
						</li>
						
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>